package cn.router.compiler.processor;

/**
 * Created to :
 *
 * @author WANG
 * @date 2018/11/5
 */

public class BaseParams {

    public static String PACKAGE_NAME ="cn.router.process";

    public static String GROUP_CLASS_NAME ="Router$Group$";
    public static String ROOT_CLASS_NAME ="Router$Root$root";

    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY WEROUTER.\n";





    public static String PACKAGE_OF_GENERATE_FILE ="cn.router.process";


    public static String ROUTER ="WeOutPutManager";
    public static String ROUTER_PARAM ="weRouter";
    public static String ROUTER_PACKAGE_path ="cn.router.api.router";

    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";

    public static final String BASEROUTER = "cn.router.api.interfaces";
    public static final String WEROUTER_GROUP_TYPE = BASEROUTER +".WeRouterGroup";
    public static final String WEROUTER_ROOT_TYPE = BASEROUTER +".WeRouterRoot";

    public static final String METHOD_INIT = "init";
    public static final String GROUP_PARAM_NAME = "groups";
    public static final String ROOT_PARAM_NAME = "roots";





}
